on: push
name: Install panda3d via pip
jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: pip install panda3d
        continue-on-error: true
      - uses: actions/setup-python@v1
        with:
          python-version: '2.x'
      - run: pip install panda3d
        continue-on-error: true
